In [1]:
# What version of Python do you have?
import sys

import tensorflow.keras
import pandas as pd
import sklearn as sk
import tensorflow as tf

print(f"Tensor Flow Version: {tf.__version__}")
print(f"Keras Version: {tensorflow.keras.__version__}")
print()
print(f"Python {sys.version}")
print(f"Pandas {pd.__version__}")
print(f"Scikit-Learn {sk.__version__}")
gpu = len(tf.config.list_physical_devices('GPU'))>0
print("GPU is", "available" if gpu else "NOT AVAILABLE")

Init Plugin
Init Graph Optimizer
Init Kernel
Tensor Flow Version: 2.5.0
Keras Version: 2.5.0

Python 3.9.7 | packaged by conda-forge | (default, Sep  2 2021, 17:55:16) 
[Clang 11.1.0 ]
Pandas 1.3.2
Scikit-Learn 0.24.2
GPU is available


In [2]:
# File handling 
#CSV
df  = pd.read_csv("https://data.heatonresearch.com/data/t81-558/iris.csv")
df[0:5]



sepal_l  sepal_w  petal_l  petal_w      species
0      5.1      3.5      1.4      0.2  Iris-setosa
1      4.9      3.0      1.4      0.2  Iris-setosa
2      4.7      3.2      1.3      0.2  Iris-setosa
3      4.6      3.1      1.5      0.2  Iris-setosa
4      5.0      3.6      1.4      0.2  Iris-setosa

In [9]:
# Stream a large CSV file
import csv
import urllib.request 
import codecs 
import numpy as np 

url = "https://data.heatonresearch.com/data/t81-558/iris.csv"
urlstream = urllib.request.urlopen(url)
csvfile = csv.reader(codecs.iterdecode(urlstream, 'utf-8'))
next(csvfile) # skip header row
sum = np.zeros(4)
count = 0

for line in csvfile:
    #Convert each row to numpy array
    line2 = np.array(line)[0:4].astype(float)

    #if the line is of right length (skip empty lines), then add
    if len (line2) == 4:
        sum += line2
        count += 1

    #calculate the average and print the average of the 4 iris measurements
    print(sum/count)

[5.1 3.5 1.4 0.2]
[5.   3.25 1.4  0.2 ]
[4.9        3.23333333 1.36666667 0.2       ]
[4.825 3.2   1.4   0.2  ]
[4.86 3.28 1.4  0.2 ]
[4.95       3.38333333 1.45       0.23333333]
[4.9        3.38571429 1.44285714 0.24285714]
[4.9125 3.3875 1.45   0.2375]
[4.85555556 3.33333333 1.44444444 0.23333333]
[4.86 3.31 1.45 0.22]
[4.90909091 3.34545455 1.45454545 0.21818182]
[4.9        3.35       1.46666667 0.21666667]
[4.89230769 3.32307692 1.46153846 0.20769231]
[4.85       3.3        1.43571429 0.2       ]
[4.91333333 3.34666667 1.42       0.2       ]
[4.9625 3.4125 1.425  0.2125]
[4.98823529 3.44117647 1.41764706 0.22352941]
[4.99444444 3.44444444 1.41666667 0.22777778]
[5.03157895 3.46315789 1.43157895 0.23157895]
[5.035 3.48  1.435 0.235]
[5.05238095 3.47619048 1.44761905 0.23333333]
[5.05454545 3.48636364 1.45       0.24090909]
[5.03478261 3.49130435 1.43043478 0.23913043]
[5.0375     3.48333333 1.44166667 0.25      ]
[5.028 3.48  1.46  0.248]
[5.02692308 3.46153846 1.46538462 0.246153

In [12]:
# Read a text file // Put a valid text file before running the code.
import urllib.request

url = "https://www.constitution.org/usdeclar.txt"
with urllib.request.urlopen(url) as stream:
    for line in codecs.iterdecode(urlstream, 'utf-8'):
        print(line.rstrip())

In [19]:
from io import BytesIO
from PIL import Image
import requests
#IMAGE

url = "https://www.static.com/webp/galley3/1.sm.png"
response = requests.get(url)
img = Image.open(BytesIO(response.content))
img